# VM for developing ReflectRPC services with Python 3.5
Vagrant.configure("2") do |config|
  config.vm.define :jsonstore_dev
  config.vm.box = "ubuntu/xenial64"

  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network "public_network"

  config.vm.network "forwarded_port", guest: 5500, host: 5500
  config.vm.network "forwarded_port", guest: 5432, host: 5432

  config.vm.provision "file", source: "../schema.sql", destination: "/tmp/schema.sql"

  #config.vm.synced_folder "../", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "jsonstore-dev"
    vb.memory = "1024"
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt update
    apt install -y --no-install-recommends \
        python3 \
        python3-dev \
        python3-pip \
        python3-setuptools \
        gcc \
        libffi-dev \
        libssl-dev \
        libssl1.0.0 \
        vim \
        postgresql \
        postgresql-contrib
    apt remove -y python3-cryptography
    sed -i "s/#listen_addresses.*/listen_addresses = '0.0.0.0'/g" /etc/postgresql/9.5/main/postgresql.conf
    echo "host all all 0.0.0.0/0 trust" >> /etc/postgresql/9.5/main/pg_hba.conf
    echo "host    all             all               0.0.0.0/0             md5" >> /etc/postgresql/9.5/main/pg_hba.conf
    sudo -u postgres psql -c "ALTER USER postgres PASSWORD postgres;"
    sudo -u postgres psql -c "CREATE EXTENSION adminpack;"
    service postgresql restart
    pip3 install reflectrpc
    sudo -u postgres psql -c 'CREATE DATABASE jsonstore'
    sudo -u postgres psql -f /tmp/schema.sql jsonstore
  SHELL
end
